// Approximate area coordinates for itinerary orientation; not verified building entrances.
const points={hotel:['ASAI Chinatown（示例酒店）',13.7435,100.5103,'ASAI Bangkok Chinatown'],bkk:['BKK 素万那普机场',13.6900,100.7501,'Suvarnabhumi Airport'],yao:['耀华力路',13.7397,100.5101,'Yaowarat Road Bangkok'],wat:['卧佛寺',13.7465,100.4927,'Wat Pho Bangkok'],krua:['Krua Apsorn Dinso',13.7559,100.5015,'Krua Apsorn Dinso Bangkok'],arun:['郑王庙',13.7437,100.4889,'Wat Arun Bangkok'],talat:['Talat Noi（替换项）',13.7330,100.5136,'Talat Noi Bangkok'],market:['空叻玛咏水上市场',13.7616,100.4154,'Khlong Lat Mayom Floating Market Bangkok'],chat:['乍都乍（可跳过）',13.7999,100.5503,'Chatuchak Weekend Market Bangkok'],night:['朱拉隆夜市 / 班塔通路',13.7392,100.5230,'Banthat Thong Chula Soi 5 Bangkok'],truth:['真理寺',12.9727,100.8893,'Sanctuary of Truth Pattaya'],beach:['Wong Amat 海边',12.9623,100.8844,'Wong Amat Beach Pattaya'],show:['Tiffany’s Show',12.9507,100.8877,'Tiffany Show Pattaya'],pier:['Bali Hai 码头区域',12.9238,100.8679,'Bali Hai Pier Pattaya'],island:['格兰岛（岛中心示意）',12.9174,100.7790,'Koh Larn Thailand'],spa:['Let’s Relax Sukhumvit 14',13.7358,100.5602,'Lets Relax Spa Sukhumvit 14 Bangkok'],noodle:['Rung Rueang Tung',13.7284,100.5706,'Rung Rueang Tung Pork Noodle 10/3 Sukhumvit 26 Bangkok'],siam:['SOS / Siam Square 区域',13.7441,100.5333,'SOS Sense of Style Siam Square Bangkok'],frank:['FRANK! GARCON Alley 2',13.7451,100.5317,'FRANK GARCON Siam Square Alley 2 Bangkok'],center:['Siam Center',13.7463,100.5323,'Siam Center Bangkok'],home:['南山中山公园区域',22.5535,113.9194,'深圳南山中山公园'],border:['深圳湾口岸',22.5035,113.9456,'Shenzhen Bay Port'],hkg:['香港机场 T2 区域',22.3150,113.9360,'Hong Kong International Airport Terminal 2']};
const routes=[
{label:'10/2 深港出发',summary:'06:15–06:30 南山出发 → 目标 09:30–09:45 到 T2。陆路时间为规划缓冲，班车集合点必须先确认。',ids:['home','border','hkg'],legs:[['打车','约 10–15 km','25–40 分钟＋通关另留 45–90 分钟','driving'],['机场直达巴士','约 40–50 km','车程约 50–80 分钟，另留候车时间','driving']]},
{label:'10/2 到达',summary:'14:55 落地后，先入住再晚饭；第一晚不跨城追网红店。',ids:['bkk','hotel','yao'],legs:[['机场出租车 / Grab','约 35–45 km','45–90 分钟以上；入境取箱另计','driving'],['步行','约 0.5–1 km','10–20 分钟','walking']]},
{label:'10/3 老城',summary:'卧佛寺 → 家常泰菜 → 郑王庙。午饭在 Dinso，不把它误写成 Dusit 米其林原店。',ids:['hotel','wat','krua','arun','hotel'],legs:[['MRT＋步行 / 打车','约 3–5 km','25–45 分钟','transit'],['打车','约 2–4 km','15–30 分钟','driving'],['打车至 Tha Tien＋渡船，或全程打车','约 3–6 km，依过河路线','30–50 分钟，天气影响渡船','driving'],['渡船＋MRT / 打车','约 4–8 km，依过河路线','30–60 分钟','transit']]},
{label:'10/4 两市场',summary:'水上市场优先；乍都乍在另一方向，累了就取消。晚间朱拉隆夜市前先回酒店休息。',ids:['hotel','market','chat','hotel','night','hotel'],legs:[['Grab / 包车','约 15–22 km','35–65 分钟','driving'],['Grab / 包车','约 25–35 km','45–90 分钟以上','driving'],['MRT / 打车','约 12–18 km','40–65 分钟','transit'],['打车','约 3–5 km','15–30 分钟','driving'],['打车','约 3–5 km','15–30 分钟','driving']]},
{label:'10/5 芭提雅 A',summary:'陆地主方案：真理寺＋海边＋秀，当晚回曼谷。长距离驾驶与司机等候须计入包车时长。',ids:['hotel','truth','beach','show','hotel'],legs:[['提前预订包车','约 145–165 km','2.5–3.5 小时','driving'],['包车','约 3–5 km','10–20 分钟','driving'],['包车','约 3–5 km','10–25 分钟','driving'],['已约定的返程包车','约 145–165 km','2.5–3.5 小时','driving']]},
{label:'10/5 海岛 B',summary:'替换方案，不代表已经选定：删真理寺，格兰岛半日后回大陆看秀。岛中心点仅示意，码头按船票确认。',ids:['hotel','pier','island','pier','show','hotel'],legs:[['包车','约 150–170 km','2.5–3.5 小时','driving'],['已确认渡船 / 正规快艇','海上约 8–12 km，依码头','航行约 20–50 分钟；候船另计',''],['预订或已确认船班返程','海上约 8–12 km','预留候船，目标 16:00 前回大陆',''],['包车','约 5–7 km','20–40 分钟','driving'],['返程包车','约 145–165 km','2.5–3.5 小时','driving']]},
{label:'10/6 按摩购物',summary:'上午 60 分钟按摩 → 米粉 → 女装小店，晚间回酒店取行李，再去 BKK。所有机场时间均为泰国当地时间。',ids:['hotel','spa','noodle','siam','frank','center','hotel','bkk'],legs:[['MRT / 打车','约 8–12 km','35–55 分钟','transit'],['BTS＋步行 / 打车','约 2–3 km','15–30 分钟','transit'],['BTS Phrom Phong → Siam＋步行','约 5–7 km','25–40 分钟','transit'],['逛街步行','约 0.2–0.5 km','5–10 分钟，不含逛店','walking'],['步行','约 0.3–0.6 km','5–12 分钟','walking'],['打车 / 轨道＋步行','约 4–6 km','20–40 分钟','driving'],['预约车辆 / Grab','约 35–45 km','60–90 分钟以上；21:30 出发为目标','driving']]},
{label:'10/7 回深圳',summary:'05:55 落地香港，完成入境取箱后再选返深班车；不把飞机落地当作上车时刻。',ids:['hkg','border','home'],legs:[['正规跨境车 / 机场巴士','约 40–50 km','车程约 50–80 分钟，候车与通关另计','driving'],['打车','约 10–15 km','25–40 分钟','driving']]}
];
let map=null,layer=null;
try{if(window.L){map=L.map('route-map',{scrollWheelZoom:false}).setView([13.75,100.52],11);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',maxZoom:18}).addTo(map).on('tileerror',()=>{document.getElementById('route-map-status').textContent='部分底图未加载，可继续查看下方地点顺序与交通，并点击 Google 实际导航。连线仅示意游览顺序。'});layer=L.layerGroup().addTo(map);}}catch{document.getElementById('route-map-status').textContent='地图加载失败，下面的交通清单和 Google 导航仍可使用。'}
const tabs=document.getElementById('route-tabs');routes.forEach((r,i)=>{const b=document.createElement('button');b.textContent=r.label;b.type='button';b.setAttribute('aria-pressed',i===2?'true':'false');b.addEventListener('click',()=>renderRoute(i));tabs.append(b);});
function renderRoute(index){const r=routes[index];[...tabs.children].forEach((b,i)=>b.setAttribute('aria-pressed',String(i===index)));document.getElementById('route-summary').textContent=r.summary;const host=document.getElementById('route-stops');host.replaceChildren();if(layer)layer.clearLayers();const coords=r.ids.map(id=>points[id].slice(1,3));if(map){L.polyline(coords,{color:'#c78b25',weight:3,dashArray:'7 7'}).addTo(layer);r.ids.forEach((id,i)=>{const p=points[id];const content=document.createElement('div');const title=document.createElement('strong');title.textContent=(i+1)+'. '+p[0];const a=document.createElement('a');a.href='https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(p[3]);a.target='_blank';a.rel='noreferrer';a.textContent='打开 Google 地图';content.append(title,document.createElement('br'),a);L.marker(p.slice(1,3),{icon:L.divIcon({className:'route-pin',html:String(i+1),iconSize:[30,30],iconAnchor:[15,15]})}).bindPopup(content).addTo(layer);});map.fitBounds(coords,{padding:[35,35],maxZoom:14});}
r.legs.forEach((leg,i)=>{const a=points[r.ids[i]],b=points[r.ids[i+1]];const row=document.createElement('div');row.className='route-leg';const head=document.createElement('strong');head.textContent=`${i+1} ${a[0]} → ${i+2} ${b[0]}`;const desc=document.createElement('span');desc.textContent=`${leg[0]} · ${leg[1]} · ${leg[2]}`;const nav=document.createElement('a');nav.target='_blank';nav.rel='noreferrer';nav.textContent=leg[3]?'实际导航 ↗':'查看目的地区域 ↗';nav.href=leg[3]?'https://www.google.com/maps/dir/?api=1&origin='+encodeURIComponent(a[3])+'&destination='+encodeURIComponent(b[3])+'&travelmode='+leg[3]:'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(b[3]);row.append(head,desc,nav);host.append(row);});}
renderRoute(2);
